# If .ini extension is used, the file should be in the following format:
# >>> [local]
# >>> localhost ansible_connection=local ansible_python_interpreter=/usr/local/bin/python
# But I prefer the .yml extension for better readability.

all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /usr/local/bin/python
