version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres-test
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      - postgres-net

  ansible:
    build:
      context: .
    container_name: ansible-controller
    volumes:
      - ./ansible:/ansible
    working_dir: /ansible
    stdin_open: true
    tty: true
    networks:
      - postgres-net
    depends_on:
      - postgres

networks:
  postgres-net:

